### GET for all players
GET http://localhost:3000/players
###

### GET for one player that exists
GET http://localhost:3000/players/702be752-b307-45bd-a63d-a05aff4e9c27
###

### GET for one player that not exists
GET http://localhost:3000/players/acf2df3
### 

### DELETE one player that exists
DELETE http://localhost:3000/players/702be752-b307-45bd-a63d-a05aff4e9c27
### 

### DELETE one player that not exists
DELETE http://localhost:3000/players/c702d4f9
### 

### POST a new player along with image
POST http://localhost:3000/players
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="data"

{
    "firstName": "Albin",
    "lastName": "Carlsson",
    "dateOfBirth": "1989-05-05",
    "nationality": "Swedish",
    "youthTeam": "Köpings IK",
    "shoots": "Vänster",
    "position": "Back",
    "height": "185",
    "weight": "89",
    "team": "Södertälje SK",
    "league": "Hockeyallsvenskan",
    "number": "15"
}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="testimage3.jpg"
Content-Type: image/jpg

< ./testimage3.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###

### POST (create) a new player with no image
POST http://localhost:3000/players
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="data"

{
    "firstName": "Daniel",
    "lastName": "Norbe",
    "dateOfBirth": "1989-05-05",
    "nationality": "Swedish",
    "youthTeam": "Karlskrona",
    "shoots": "Vänster",
    "position": "Back",
    "height": "192",
    "weight": "99",
    "team": "Södertälje SK",
    "league": "Hockeyallsvenskan",
    "number": "27"
}
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###

### PUT (update) a new player along with image
PUT http://localhost:3000/players/702be752-b307-45bd-a63d-a05aff4e9c27
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="data"

{
   "id": "702be752-b307-45bd-a63d-a05aff4e9c27",
    "firstName": "Dragan",
    "lastName": "Umicevic",
    "dateOfBirth": "1984-10-09",
    "nationality": "Swedish",
    "youthTeam": "Köpings IK",
    "shoots": "Höger",
    "position": "Forward",
    "height": "185",
    "weight": "89",
    "team": "Södertälje SK",
    "league": "Hockeyallsvenskan",
    "number": "84",
    "image": ""
}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="testimage.jpg"
Content-Type: image/jpg

< ./testimage.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###

### PUT (update) a new player with no image
PUT http://localhost:3000/players/702be752-b307-45bd-a63d-a05aff4e9c27
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="data"

{
   "id": "702be752-b307-45bd-a63d-a05aff4e9c27",
    "firstName": "Dragan",
    "lastName": "Umicevic",
    "dateOfBirth": "1984-10-09",
    "nationality": "Swedish",
    "youthTeam": "Köpings IK",
    "shoots": "Höger",
    "position": "Forward",
    "height": "186",
    "weight": "89",
    "team": "Södertälje SK",
    "league": "Hockeyallsvenskan",
    "number": "84",
    "image": ""
}

------WebKitFormBoundary7MA4YWxkTrZu0gW--
###
